/**
 * Canonical chart metric registry: single source for pipeline order, Sankey layout hints, and `compute` wiring.
 * Imported by {@link chartMetricsRegistry} for metric-line evaluation and derived constants.
 */
import type { TaxYearConfig } from "~/lib/taxData.types";
import { FEDERAL_CREDIT_CONFIGS, PRETAX_BENEFIT_CONFIGS } from "~/lib/config/taxItems";
import type { ChartRegistryEntry } from "./chartMetricsRegistry";
import {
  accreteDeduction,
  accreteFederalLtcg,
  accreteFederalOrdinary,
  accreteIncome,
  accreteNiit,
  accretePayroll,
  accretePretax,
  accreteSelfEmployment,
  accreteTakeHome,
  accreteTaxCredits,
  federalCreditSummary,
  incomeSummary,
  pretaxSummaryRow,
} from "./chartMetricRegistryCompute";

export const TAX_CALC_REGISTRY: readonly ChartRegistryEntry[] = [
  {
    metricsKey: "totalIncome",
    valueKind: "number",
    visualizationSourceId: "total-income",
    sankey: {
      structuralNode: {
        kind: "incomeSource",
        order: 0,
        column: 0,
        fill: "var(--sankey-node-income)",
        linkStroke: "var(--sankey-link)",
      },
    },
    summary: { summaryId: "total-income", label: "Total Income", category: "income", displayOrder: 6 },
    detailedDisplay: {
      order: 105,
      type: "total-income",
      category: "income",
      label: "Total Income",
      tooltip: "Gross income from all sources",
      color: "#166534",
    },
    compute: (ctx) => accreteIncome(ctx).totalIncome,
  },
  {
    metricsKey: "wageIncome",
    valueKind: "number",
    visualizationSourceId: "wages",
    sankey: { incomeKindVerticalOrder: 3 },
    summary: incomeSummary("wages", 1),
    detailedDisplay: { order: 100, type: "wages", category: "income" },
    compute: (ctx) => accreteIncome(ctx).wageIncome,
  },
  {
    metricsKey: "selfEmploymentIncome",
    valueKind: "number",
    visualizationSourceId: "selfEmployment",
    sankey: { incomeKindVerticalOrder: 2 },
    summary: incomeSummary("selfEmployment", 2),
    detailedDisplay: { order: 101, type: "selfemployment", category: "income" },
    compute: (ctx) => accreteIncome(ctx).selfEmploymentIncome,
  },
  {
    metricsKey: "ordinaryGrossIncome",
    valueKind: "number",
    visualizationSourceId: "ordinary",
    sankey: { incomeKindVerticalOrder: 4 },
    summary: incomeSummary("ordinary", 3),
    detailedDisplay: { order: 102, type: "ordinary", category: "income" },
    compute: (ctx) => {
      const i = accreteIncome(ctx);
      return i.ordinaryIncome + i.shortTermCapGains;
    },
  },
  {
    metricsKey: "shortTermCapGainsGrossIncome",
    valueKind: "number",
    visualizationSourceId: "shortTermCapGains",
    sankey: { incomeKindVerticalOrder: 1 },
    summary: incomeSummary("shortTermCapGains", 4),
    detailedDisplay: { order: 103, type: "shorttermcapgains", category: "income" },
    compute: (ctx) => accreteIncome(ctx).shortTermCapGains,
  },
  {
    metricsKey: "longTermCapitalGainsGrossIncome",
    valueKind: "number",
    visualizationSourceId: "longTermCapGains",
    sankey: {
      incomeKindVerticalOrder: 0,
      structuralNode: {
        kind: "ltcgDeductionShield",
        order: 1,
        column: 1,
        fill: "var(--sankey-node-ltcg)",
        linkStroke: "var(--sankey-link)",
      },
    },
    summary: incomeSummary("longTermCapGains", 5),
    detailedDisplay: { order: 104, type: "longtermcapgains", category: "income" },
    compute: (ctx) => accreteIncome(ctx).longTermCapGains,
  },
  {
    metricsKey: "preTax401k",
    valueKind: "number",
    visualizationSourceId: "preTax401k",
    sankey: {
      structuralNode: {
        kind: "deferredSink",
        order: 16,
        /** Past pretax bars + shield so d3-sankey layers stay strictly income → pretax → shield → deferred (not same layer as {@link preTaxTotal} pretaxContribution). */
        column: 4,
        fill: "var(--sankey-node-deferred)",
        linkStroke: "var(--sankey-link-deferred)",
      },
    },
    summary: pretaxSummaryRow(PRETAX_BENEFIT_CONFIGS[0], 7),
    detailedDisplay: { order: 106, type: "401k", category: "pretax" },
    compute: (ctx) => accretePretax(ctx)["401k"],
  },
  {
    metricsKey: "preTaxHsa",
    valueKind: "number",
    visualizationSourceId: "preTaxHsa",
    summary: pretaxSummaryRow(PRETAX_BENEFIT_CONFIGS[1], 8),
    detailedDisplay: { order: 107, type: "hsa", category: "pretax" },
    compute: (ctx) => accretePretax(ctx).hsa,
  },
  {
    metricsKey: "preTaxOther",
    valueKind: "number",
    visualizationSourceId: "preTaxOther",
    summary: pretaxSummaryRow(PRETAX_BENEFIT_CONFIGS[3], 10),
    detailedDisplay: { order: 109, type: "other", category: "pretax" },
    compute: (ctx) => accretePretax(ctx).other,
  },
  {
    metricsKey: "preTaxTotal",
    valueKind: "number",
    visualizationSourceId: "preTaxTotal",
    sankey: {
      structuralNode: {
        kind: "pretaxContribution",
        order: 6,
        /** Same semantic column as ordinary taxable / standard deduction (second strip from income), not bracket column. */
        column: 1,
        fill: "var(--sankey-node-keep)",
        linkStroke: "var(--sankey-link)",
      },
    },
    detailedDisplay: {
      order: 110,
      type: "total-pretax",
      category: "pretax",
      label: "Total Pre-tax",
      tooltip: "Total pre-tax deductions",
      color: "#7e22ce",
    },
    compute: (ctx) => accretePretax(ctx).amount,
  },
  {
    metricsKey: "traditionalIra",
    valueKind: "number",
    visualizationSourceId: "traditionalIra",
    summary: pretaxSummaryRow(PRETAX_BENEFIT_CONFIGS[2], 9),
    detailedDisplay: { order: 108, type: "traditional-ira", category: "pretax" },
    compute: (ctx) => accretePretax(ctx).traditionalIra,
  },
  {
    metricsKey: "wagesAfterPretax",
    valueKind: "number",
    visualizationSourceId: "wages-after-pretax",
    sankey: {
      structuralNode: {
        kind: "deductionBenefitSink",
        order: 11,
        column: 1,
        fill: "var(--sankey-node-keep)",
        linkStroke: "var(--sankey-link-keep)",
        fillBenefitAccounting: "var(--sankey-node-deferred)",
        linkStrokeBenefitAccounting: "var(--sankey-link-deferred)",
      },
    },
    summary: {
      summaryId: "wages-after-pretax",
      label: "Wages After Pre-tax",
      category: "pretax",
      displayOrder: 11,
    },
    detailedDisplay: {
      order: 111,
      type: "wages-after-pretax",
      category: "pretax",
      tooltip: "Wages after pre-tax deductions",
      color: "#9333ea",
    },
    compute: (ctx) => accretePretax(ctx).wagesAfterPretax,
  },
  {
    metricsKey: "standardDeduction",
    valueKind: "number",
    visualizationSourceId: "standard-deduction",
    sankey: {
      structuralNode: {
        kind: "standardDeduction",
        order: 4,
        column: 1,
        fill: "var(--sankey-node-2)",
        linkStroke: "var(--sankey-link)",
      },
    },
    summary: { summaryId: "standard-deduction", label: "Standard Deduction", category: "deduction", displayOrder: 12 },
    detailedDisplay: { order: 112, type: "standard-deduction", category: "deduction" },
    compute: (ctx) => accreteDeduction(ctx).standardDeduction,
  },
  {
    metricsKey: "deductionAmount",
    valueKind: "number",
    visualizationSourceId: "deduction-amount",
    sankey: {
      structuralNode: {
        kind: "deduction",
        order: 9.5,
        column: 3,
        fill: "var(--sankey-node-2)",
        linkStroke: "var(--sankey-link)",
      },
    },
    mekko: { role: "deduction", usesSegments: false },
    summary: { summaryId: "deduction-amount", label: "Deduction Used", category: "deduction", displayOrder: 13 },
    detailedDisplay: {
      order: 113,
      type: "deduction-used",
      category: "deduction",
      tooltip: "Higher of standard or itemized",
      color: "#d97706",
    },
    compute: (ctx) => accreteDeduction(ctx).amount,
  },
  {
    metricsKey: "ordinaryTaxableIncome",
    valueKind: "number",
    visualizationSourceId: "ordinary-taxable-income",
    sankey: {
      structuralNodes: [
        {
          kind: "ordinaryTaxableIncome",
          order: 3,
          column: 1,
          fill: "var(--sankey-node-3)",
          linkStroke: "var(--sankey-link)",
        },
        {
          kind: "payrollOrdinaryStrip",
          order: 8,
          column: 3,
          fill: "var(--sankey-node-deferred)",
          linkStroke: "var(--sankey-link-deferred)",
        },
      ],
    },
    summary: { summaryId: "ordinary-taxable-income", label: "Ordinary Taxable", category: "income", displayOrder: 14 },
    detailedDisplay: {
      order: 113,
      type: "ordinary-taxable-income",
      category: "tax",
      label: "Ordinary Taxable Income",
    },
    compute: (ctx) => accreteFederalOrdinary(ctx).ordinaryTaxableIncome,
  },
  {
    metricsKey: "longTermTaxableIncome",
    valueKind: "number",
    visualizationSourceId: "long-term-taxable-income",
    sankey: {
      structuralNode: {
        kind: "longTermTaxableIncome",
        order: 2,
        column: 1,
        fill: "var(--sankey-node-ltcg)",
        linkStroke: "var(--sankey-link)",
      },
    },
    summary: { summaryId: "long-term-taxable-income", label: "LTCG Taxable", category: "income", displayOrder: 10 },
    detailedDisplay: {
      order: 110,
      type: "ltcg-taxable-income",
      category: "tax",
      label: "LTCG Taxable Income",
    },
    compute: (ctx) => accreteFederalLtcg(ctx).longTermTaxableIncome,
  },
  {
    metricsKey: "taxableIncome",
    valueKind: "number",
    sankey: {
      structuralNode: {
        kind: "deductionShield",
        order: 10,
        /** One step right of pretax middle bars so shield is not the same layer as {@link preTaxTotal} pretaxContribution. */
        column: 3,
        fill: "var(--sankey-node-5)",
        linkStroke: "var(--sankey-link)",
      },
    },
    compute: (ctx) =>
      accreteFederalOrdinary(ctx).ordinaryTaxableIncome + accreteFederalLtcg(ctx).longTermTaxableIncome,
  },
  {
    metricsKey: "ordinaryFederalSegments",
    valueKind: "segments",
    sankey: {
      sankeyNodeKind: "ordinaryBracket",
      chartCategory: "tax",
      structuralNode: {
        kind: "ordinaryBracket",
        order: 11,
        column: 3,
        fill: "var(--sankey-node-4)",
        linkStroke: "var(--sankey-link)",
      },
    },
    mekko: { role: "ordinaryBracket", usesSegments: true },
    compute: (ctx) => accreteFederalOrdinary(ctx).segments,
  },
  {
    metricsKey: "longTermCapitalGainsSegments",
    valueKind: "segments",
    sankey: {
      sankeyNodeKind: "ltcgBracket",
      chartCategory: "tax",
      structuralNode: {
        kind: "ltcgBracket",
        order: 8,
        column: 3,
        fill: "var(--sankey-node-ltcg)",
        linkStroke: "var(--sankey-link)",
      },
    },
    mekko: { role: "ltcgBracket", usesSegments: true },
    compute: (ctx) =>
      accreteFederalLtcg(ctx).segments.map((seg) => ({
        rangeStart: seg.rangeStart,
        rangeEnd: seg.rangeEnd,
        incomeAmount: seg.incomeAmount,
        taxAmount: seg.taxAmount,
        marginalRate: seg.rate,
      })),
  },
  {
    metricsKey: "federalOrdinaryIncomeTax",
    valueKind: "number",
    visualizationSourceId: "federal-ordinary-tax",
    sankey: { sankeyNodeKind: "ordinaryBracket", chartCategory: "tax" },
    summary: { summaryId: "federal-ordinary-tax", label: "Federal Ord. Tax", category: "tax", displayOrder: 16 },
    detailedDisplay: {
      order: 116,
      type: "federal-ordinary-tax",
      category: "tax",
      label: "Federal Ordinary Tax",
      tooltip: "Federal income tax on ordinary income",
    },
    compute: (ctx) => accreteFederalOrdinary(ctx).amount,
  },
  {
    metricsKey: "federalLongTermCapGainsTax",
    valueKind: "number",
    visualizationSourceId: "federal-ltcg-tax",
    sankey: { sankeyNodeKind: "ltcgBracket", chartCategory: "tax" },
    summary: { summaryId: "federal-ltcg-tax", label: "Federal LTCG Tax", category: "tax", displayOrder: 17 },
    detailedDisplay: {
      order: 117,
      type: "federal-ltcg-tax",
      category: "tax",
      label: "Federal LTCG Tax",
      tooltip: "Federal tax on long-term capital gains",
    },
    compute: (ctx) => accreteFederalLtcg(ctx).amount,
  },
  {
    metricsKey: "federalNetInvestmentIncomeTax",
    valueKind: "number",
    visualizationSourceId: "federal-niit",
    summary: { summaryId: "federal-niit", label: "Net Investment Income Tax", category: "tax", displayOrder: 18 },
    detailedDisplay: {
      order: 118,
      type: "federal-niit",
      category: "tax",
      label: "Net Investment Income Tax",
      tooltip: "3.8% NIIT on investment income",
    },
    compute: (ctx) => accreteNiit(ctx).amount,
  },
  {
    metricsKey: "netInvestmentIncome",
    valueKind: "number",
    compute: (ctx) => accreteNiit(ctx).netInvestmentIncome,
  },
  {
    metricsKey: "federalIncomeTaxBeforeCredits",
    valueKind: "number",
    visualizationSourceId: "federal-income-tax-before-credits",
    summary: {
      summaryId: "federal-income-tax-before-credits",
      label: "Fed Tax Before Credits",
      category: "tax",
      displayOrder: 20,
    },
    detailedDisplay: {
      order: 119,
      type: "federal-income-tax",
      category: "tax",
      label: "Federal Income Tax (before credits)",
      tooltip: "Total federal income tax before credits",
      color: "#dc2626",
    },
    compute: (ctx) => accreteTaxCredits(ctx).totalTaxLiability,
  },
  {
    metricsKey: "federalTaxCredits",
    valueKind: "number",
    compute: (ctx) => accreteTaxCredits(ctx).creditsEntered,
  },
  {
    metricsKey: "federalTaxCreditsApplied",
    valueKind: "number",
    sankey: {
      sankeyNodeKind: "federalCredits",
      chartCategory: "tax",
      structuralNode: {
        kind: "federalCredits",
        order: 14,
        column: 4,
        fill: "var(--sankey-node-credits)",
        linkStroke: "var(--sankey-link-credits)",
      },
      terminalId: "federal-credits",
    },
    compute: (ctx) => accreteTaxCredits(ctx).creditsApplied,
  },
  {
    metricsKey: "federalIncomeTax",
    valueKind: "number",
    visualizationSourceId: "federal-income-tax",
    sankey: {
      structuralNode: {
        kind: "taxesFederal",
        order: 13,
        column: 4,
        fill: "var(--sankey-node-6)",
        linkStroke: "var(--sankey-link-tax)",
      },
      terminalId: "taxes-federal",
    },
    summary: { summaryId: "federal-income-tax", label: "Federal Income Tax", category: "tax", displayOrder: 19 },
    detailedDisplay: {
      order: 120,
      type: "federal-income-tax-after-credits",
      category: "tax",
      label: "Federal Income Tax",
      tooltip: "Federal income tax after credits",
      highlight: true,
      color: "#b91c1c",
    },
    compute: (ctx) => accreteTaxCredits(ctx).federalIncomeTaxAfterCredits,
  },
  {
    metricsKey: "payrollTax",
    valueKind: "number",
    visualizationSourceId: "payroll-tax",
    sankey: {
      sankeyNodeKind: "taxesPayroll",
      chartCategory: "tax",
      structuralNode: {
        kind: "taxesPayroll",
        order: 10,
        column: 4,
        fill: "var(--sankey-node-6)",
        linkStroke: "var(--sankey-link-tax)",
      },
      terminalId: "taxes-payroll",
    },
    summary: { summaryId: "payroll-tax", label: "Payroll Taxes", category: "tax", displayOrder: 28 },
    detailedDisplay: {
      order: 123,
      type: "payroll-tax",
      category: "tax",
      label: "Payroll Taxes",
      tooltip: "Social Security and Medicare",
      color: "#1d4ed8",
    },
    compute: (ctx) => accretePayroll(ctx).amount,
  },
  {
    metricsKey: "selfEmploymentTax",
    valueKind: "number",
    visualizationSourceId: "self-employment-tax",
    sankey: {
      sankeyNodeKind: "taxesPayroll",
      chartCategory: "tax",
      structuralNode: {
        kind: "taxesPayroll",
        order: 10,
        column: 4,
        fill: "var(--sankey-node-6)",
        linkStroke: "var(--sankey-link-tax)",
      },
      terminalId: "taxes-payroll",
    },
    summary: {
      summaryId: "self-employment-tax",
      label: "Self-Employment Tax",
      category: "tax",
      displayOrder: 27,
      hideWhenZero: true,
    },
    detailedDisplay: {
      order: 123,
      type: "self-employment-tax",
      category: "tax",
      label: "Self-Employment Tax",
      tooltip: "Social Security and Medicare on net self-employment earnings (SECA)",
      color: "#1d4ed8",
    },
    compute: (ctx) => accreteSelfEmployment(ctx).amount,
  },
  {
    metricsKey: "socialSecurityTax",
    valueKind: "number",
    visualizationSourceId: "social-security-tax",
    summary: { summaryId: "social-security-tax", label: "Social Security Tax", category: "tax", displayOrder: 25 },
    detailedDisplay: { order: 121, type: "social-security-tax", category: "tax", label: "Social Security Tax", color: "#3b82f6" },
    compute: (ctx) => accretePayroll(ctx).socialSecurityTax,
  },
  {
    metricsKey: "medicareTax",
    valueKind: "number",
    visualizationSourceId: "medicare-tax",
    summary: { summaryId: "medicare-tax", label: "Medicare Tax", category: "tax", displayOrder: 26 },
    detailedDisplay: { order: 122, type: "medicare-tax", category: "tax", label: "Medicare Tax", color: "#3b82f6" },
    compute: (ctx) => accretePayroll(ctx).medicareTax,
  },
  {
    metricsKey: "takeHomePay",
    valueKind: "number",
    visualizationSourceId: "take-home-pay",
    sankey: {
      sankeyNodeKind: "keep",
      chartCategory: "keep",
      structuralNode: {
        kind: "keep",
        order: 15,
        column: 4,
        fill: "var(--sankey-node-keep)",
        linkStroke: "var(--sankey-link-keep)",
      },
      terminalId: "keep",
    },
    summary: {
      summaryId: "take-home-pay",
      label: "Take-Home Pay",
      category: "takehome",
      displayOrder: 29,
      highlight: true,
    },
    detailedDisplay: {
      order: 128,
      type: "take-home-pay",
      category: "summary",
      label: "Take-Home Pay",
      tooltip: "Income after all taxes and deductions",
      highlight: true,
    },
    compute: (ctx) => accreteTakeHome(ctx).amount,
  },
  {
    metricsKey: "effectiveTaxRate",
    valueKind: "number",
    visualizationSourceId: "effective-rate",
    summary: {
      summaryId: "effective-rate",
      label: "Effective Tax Rate",
      category: "rate",
      displayOrder: 30,
      format: "percent",
      highlight: true,
    },
    detailedDisplay: {
      order: 129,
      type: "effective-tax-rate",
      category: "summary",
      label: "Effective Tax Rate",
      format: "percent",
      tooltip: "Total tax / taxable income",
      highlight: true,
      color: "#0f766e",
    },
    compute: (ctx) => accreteTakeHome(ctx).effectiveRate,
  },
  {
    metricsKey: "childTaxCredit",
    valueKind: "number",
    summary: federalCreditSummary(FEDERAL_CREDIT_CONFIGS[0], 21),
    detailedDisplay: {
      order: 124,
      type: "childTaxCredit-credit",
      category: "credit",
      label: FEDERAL_CREDIT_CONFIGS[0]!.label,
      color: "#14b8a6",
    },
    compute: (ctx) => accreteTaxCredits(ctx).childTaxCredit,
  },
  {
    metricsKey: "educationCredits",
    valueKind: "number",
    summary: federalCreditSummary(FEDERAL_CREDIT_CONFIGS[1], 22),
    detailedDisplay: {
      order: 125,
      type: "educationCredits-credit",
      category: "credit",
      label: FEDERAL_CREDIT_CONFIGS[1]!.label,
      color: "#14b8a6",
    },
    compute: (ctx) => accreteTaxCredits(ctx).educationCredits,
  },
  {
    metricsKey: "retirementSavings",
    valueKind: "number",
    summary: federalCreditSummary(FEDERAL_CREDIT_CONFIGS[2], 23),
    detailedDisplay: {
      order: 126,
      type: "retirementSavingsContributions-credit",
      category: "credit",
      label: FEDERAL_CREDIT_CONFIGS[2]!.label,
      color: "#14b8a6",
    },
    compute: (ctx) => accreteTaxCredits(ctx).retirementSavings,
  },
  {
    metricsKey: "federalCreditOther",
    valueKind: "number",
    summary: federalCreditSummary(FEDERAL_CREDIT_CONFIGS[3], 24),
    detailedDisplay: {
      order: 127,
      type: "other-credit",
      category: "credit",
      label: FEDERAL_CREDIT_CONFIGS[3]!.label,
      color: "#14b8a6",
    },
    compute: (ctx) => accreteTaxCredits(ctx).other,
  },
  {
    metricsKey: "marginalFederalRate",
    valueKind: "number",
    summary: {
      summaryId: "marginal-rate",
      label: "Marginal Rate",
      category: "rate",
      displayOrder: 31,
      format: "percent",
    },
    detailedDisplay: {
      order: 130,
      type: "marginal-tax-rate",
      category: "summary",
      label: "Marginal Tax Rate",
      format: "percent",
      tooltip: "Highest federal ordinary bracket",
      color: "#115e59",
    },
    compute: (ctx) => accreteTakeHome(ctx).marginalFederalRate,
  },
];

export function makeTaxCalcRegistry(taxYearConfig: TaxYearConfig): ChartRegistryEntry[] {
  void taxYearConfig;
  return [...TAX_CALC_REGISTRY];
}
